import { isFirebaseConfigured, observeAuth, signInWithEmail, signOutUser, signUpWithEmail } from './firebase-auth.js';
import { postComment, subscribeToComments } from './firebase-comments.js';
const patterns=[['Cute Amigurumi Teddy Bear','Amigurumi','Beginner','https://images.unsplash.com/photo-1566576912327-7f7e1d2e3343?auto=format&fit=crop&w=600&q=80'],['Cozy Chunky Baby Blanket','Blankets','Beginner','https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=600&q=80'],['Winter Ribbed Beanie Hat','Accessories','Intermediate','https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?auto=format&fit=crop&w=600&q=80'],['Sunflower Table Coasters','Home decor','Beginner','https://images.unsplash.com/photo-1608032077018-c9aad9565d29?auto=format&fit=crop&w=600&q=80'],['Cloudy Day Cardigan','Sweater','Advanced','https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=600&q=80'],['Little Lamb Rattle','Amigurumi','Intermediate','https://images.unsplash.com/photo-1597484661643-2f5fef640dd1?auto=format&fit=crop&w=600&q=80'],['Sunday Market Tote','Accessories','Beginner','https://images.unsplash.com/photo-1558171813-4c088753af8f?auto=format&fit=crop&w=600&q=80'],['Meadow Throw Pillow','Home decor','Intermediate','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&q=80'],['Heirloom Ripple Throw','Blankets','Advanced','https://images.unsplash.com/photo-1583845112203-454c7f519344?auto=format&fit=crop&w=600&q=80'],['Blooming Granny Square','Home decor','Beginner','https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=600&q=80'],['Coastal Pullover','Sweater','Advanced','https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=600&q=80'],['Pocket Fox Friend','Amigurumi','Intermediate','https://images.unsplash.com/photo-1588421357574-87938a86fa28?auto=format&fit=crop&w=600&q=80']];
const ADMIN_EMAILS=['virkacrafts@gmail.com'];
let page=1, saved=JSON.parse(localStorage.getItem('virka-saved')||'[]'), user=null, loadedGuides=[], unsubscribeComments=()=>{};const $=s=>document.querySelector(s);const grid=$('#patternGrid');
function notify(message,type='info'){const notice=$('#authNotice');notice.textContent=message;notice.className=`auth-notice ${type}`;notice.hidden=false;clearTimeout(window.virkaNoticeTimer);window.virkaNoticeTimer=setTimeout(()=>notice.hidden=true,6500)}
function draw(){let q=$('#patternSearch').value.toLowerCase(),d=$('#difficulty').value,c=$('#category').value;let list=patterns.filter(x=>(x[0]+x[1]).toLowerCase().includes(q)&&(d==='all'||x[2]===d)&&(c==='all'||x[1]===c));grid.innerHTML=list.slice(0,page*8).map((x,i)=>`<article class="pattern-card"><div class="card-img"><img src="${x[3]}" alt="${x[0]}"><button class="heart" data-i="${patterns.indexOf(x)}">${saved.includes(patterns.indexOf(x))?'♥':'♡'}</button></div><div class="details"><span class="tag">${x[1]} · ${x[2]}</span><h3>${x[0]}</h3><button class="guide" data-view="${patterns.indexOf(x)}">View pattern guide →</button></div></article>`).join('');$('#loadMore').style.display=list.length>page*8?'block':'none'}draw();
['#patternSearch','#difficulty','#category'].forEach(s=>$(s).addEventListener('input',()=>{page=1;draw()}));$('#loadMore').onclick=()=>{page++;draw()};grid.onclick=e=>{let i=e.target.dataset.i;if(i!==undefined){if(!user)return openAuth('login','Please log in to save patterns.');saved.includes(+i)?saved=saved.filter(n=>n!=i):saved.push(+i);localStorage.setItem('virka-saved',JSON.stringify(saved));draw()}let v=e.target.dataset.view;if(v!==undefined)openPattern(+v)};
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]))}
function renderComments(targetId){const host=$('#commentsHost');if(!host)return;unsubscribeComments();const drawComments=comments=>{host.querySelector('.comment-list').innerHTML=comments.length?comments.map(comment=>`<article><b>${escapeHtml(comment.userName||'VirkaCrafts member')}</b><p>${escapeHtml(comment.text||'')}</p></article>`).join(''):'<p>No comments yet. Be the first to share a tip.</p>'};host.innerHTML=`<div class="comment"><b>Comments & feedback</b>${user?`<form id="commentForm"><textarea id="commentText" placeholder="Write a comment..." required></textarea><button class="soft-btn">Post comment</button></form>`:'<p>Please log in to leave a comment.</p>'}<div class="comment-list"><p>Loading comments…</p></div></div>`;unsubscribeComments=subscribeToComments(targetId,drawComments,error=>{host.querySelector('.comment-list').innerHTML=`<p>${escapeHtml(error.message||'Comments could not be loaded.')}</p>`});const form=$('#commentForm');if(form)form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;try{await postComment(targetId,$('#commentText').value);$('#commentText').value=''}catch(error){alert(error.message||'Could not post the comment.')}finally{button.disabled=false}}}
function openPattern(i){let p=patterns[i],locked=p[2]==='Advanced'&&!user,targetId=p[5]||`pattern-${i}`;$('#modalContent').innerHTML=`<img class="detail-image" src="${p[3]}" alt=""><h2>${p[0]}</h2><p class="tag">${p[1]} · ${p[2]}</p><p>Make this lovely piece at your own pace with our illustrated step-by-step guide.</p>${locked?'<button class="coral-btn" data-auth="login">Log in to view advanced guide</button>':p[4]?`<a class="coral-btn pdf-link" href="${p[4]}" target="_blank" rel="noopener">View / download PDF</a>`:'<button class="coral-btn" id="download">Free Download PDF</button>'}<div id="commentsHost"></div>`;modal.showModal();renderComments(targetId)}
const modal=$('#modal');$('#closeModal').onclick=()=>{unsubscribeComments();modal.close()};document.addEventListener('click',e=>{if(e.target.dataset.auth)openAuth(e.target.dataset.auth);if(e.target.id==='download')alert('Demo download: connect this button to your pattern PDF in Sanity Studio.')});
function openAuth(type,msg=''){let signup=type==='signup';$('#modalContent').innerHTML=`<h2>${signup?'Join VirkaCrafts':'Welcome back'}</h2><p>${msg||'Save your favorite makes and unlock free advanced learning.'}</p><form class="modal-form" id="authForm">${signup?'<input type="text" id="signup-name" placeholder="Full Name" required autocomplete="name">':''}<input required id="email" type="email" placeholder="Email address" autocomplete="email"><div class="password-field"><input required id="authPassword" type="password" placeholder="Password" minlength="6" autocomplete="${signup?'new-password':'current-password'}"><button type="button" class="password-toggle" id="passwordToggle" aria-label="Show password" aria-pressed="false"><span aria-hidden="true">👁</span></button></div><button>${signup?'Create account & verify email':'Log in'}</button></form>`;modal.showModal();const passwordInput=$('#authPassword'),passwordToggle=$('#passwordToggle');passwordToggle.onclick=()=>{const isVisible=passwordInput.type==='text';passwordInput.type=isVisible?'password':'text';passwordToggle.setAttribute('aria-label',isVisible?'Show password':'Hide password');passwordToggle.setAttribute('aria-pressed',String(!isVisible));passwordToggle.querySelector('span').textContent=isVisible?'👁':'◉'};$('#authForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button[type="submit"],button:not(.password-toggle)'),email=$('#email').value,password=passwordInput.value,name=signup?$('#signup-name').value.trim():'';if(!isFirebaseConfigured){alert('Firebase setup is incomplete. Add the Firebase web-app values to firebase-config.js first.');return}button.disabled=true;try{if(signup){await signUpWithEmail(name,email,password);sessionStorage.setItem('virka-pending-verification','true');$('#modalContent').innerHTML=`<h2>Check your email</h2><p>We sent a verification link to <b>${email}</b>. Open the link, then return here and log in.</p>`}else{let result=await signInWithEmail(email,password);if(!result.verified){$('#modalContent').innerHTML=`<h2>Verify your email</h2><p>Please verify your email address via the link sent to your inbox before signing in.</p>`;notify('Please verify your email address via the link sent to your inbox before signing in.','warning')}else{finish(result.user);notify('Email verified successfully! You are now signed in.','success')}}}catch(error){alert(error.message||'Authentication failed. Please try again.')}finally{button.disabled=false}}}
function finish(firebaseUser){user={uid:firebaseUser.uid,name:firebaseUser.displayName||firebaseUser.email,email:firebaseUser.email,isAdmin:ADMIN_EMAILS.includes((firebaseUser.email||'').toLowerCase())};$('#profile span').textContent=user.name;document.querySelectorAll('[data-auth]').forEach(x=>x.classList.add('hidden'));$('#profile').classList.remove('hidden');$('#adminPublish').classList.toggle('hidden',!user.isAdmin);modal.close()}
function clearUser(){user=null;$('#profile').classList.add('hidden');$('#accountMenu').classList.add('hidden');document.querySelectorAll('[data-auth]').forEach(x=>x.classList.remove('hidden'));}
observeAuth(firebaseUser=>{if(!firebaseUser){clearUser();return}if(!firebaseUser.emailVerified){clearUser();signOutUser();notify('Please verify your email address via the link sent to your inbox before signing in.','warning');return}finish(firebaseUser);if(sessionStorage.getItem('virka-pending-verification')){sessionStorage.removeItem('virka-pending-verification');notify('Email verified successfully! You are now signed in.','success')}});
$('#savedBtn').onclick=()=>{page=99;$('#patternSearch').value='';$('#difficulty').value='all';$('#category').value='all';grid.innerHTML='';let old=patterns.filter((_,i)=>saved.includes(i));if(!old.length){alert('No saved patterns yet — tap a heart on any pattern card.');return}grid.innerHTML=old.map(x=>`<article class="pattern-card"><div class="card-img"><img src="${x[3]}" alt="${x[0]}"></div><div class="details"><span class="tag">${x[1]}</span><h3>${x[0]}</h3></div></article>`).join('')};
const stitches=[['Chain stitch','ch','ch'],['Slip stitch','sl st','sl st'],['Single crochet','sc','dc'],['Half double crochet','hdc','htr'],['Double crochet','dc','tr'],['Treble crochet','tr','dtr']];$('#stitchTable').innerHTML=`<div class="stitch-row head"><span>Sample</span><span>Name & symbol</span><span>Drawing</span><span>US code</span><span>UK code</span><span>How to make</span><span></span></div>`+stitches.map((x,i)=>`<div class="stitch-row"><div class="stitch-sample"><i class="swatch" style="filter:hue-rotate(${i*35}deg)"></i></div><div class="guide-name"><b>${x[0]}</b><span class="guide-symbol">${x[1]}</span></div><div class="stitch-drawing drawing-placeholder">—</div><span class="stitch-code">${x[1]}</span><span class="stitch-code">${x[2]}</span><div class="steps"><i></i><i></i><i></i></div><button class="read" data-stitch="${x[0]}">Read instructions</button></div>`).join('');
function openImageLightbox(src,alt='Image preview'){$('#modalContent').innerHTML=`<img class="lightbox-image" src="${src}" alt="${alt}">`;modal.showModal()}
function plainInstructions(blocks=[]){return blocks.map(block=>(block.children||[]).map(child=>child.text||'').join('')).filter(Boolean).join('\n\n')}
function openGuide(guide){const instructions=plainInstructions(guide.instructions)||'No written instructions have been added yet.';$('#modalContent').innerHTML=`<h2>${guide.title||'Stitch guide'}</h2>${guide.sampleImage?`<img class="detail-image zoomable" data-zoom="${guide.sampleImage}" src="${guide.sampleImage}" alt="${guide.title||'Stitch'} sample">`:''}<p class="tag">${guide.level||'Basic'} · US: ${guide.us} · UK: ${guide.uk}</p><p class="instruction-copy">${instructions.replaceAll('\n','<br>')}</p>${guide.instructionPdf?`<a class="coral-btn pdf-link" href="${guide.instructionPdf}" target="_blank" rel="noopener">View / download PDF</a>`:''}`;modal.showModal()}
$('#stitchTable').onclick=e=>{const image=e.target.closest('[data-zoom]');if(image){openImageLightbox(image.dataset.zoom,image.alt);return}if(e.target.dataset.guide!==undefined){openGuide(loadedGuides[Number(e.target.dataset.guide)]);return}if(e.target.dataset.stitch){$('#modalContent').innerHTML=`<h2>${e.target.dataset.stitch}</h2><p>Start with a relaxed loop, work into the indicated stitch, then pull yarn through smoothly. Practice a small swatch until your tension feels comfortable.</p>`;modal.showModal()}};$('#advancedBtn').onclick=()=>user?alert('Advanced stitch guide is ready for your account.'):openAuth('signup','Create a free account to access advanced learning materials.');
const hooks=[['2.0 mm','B / 1','14'],['3.5 mm','E / 4','9'],['4.0 mm','G / 6','8'],['5.0 mm','H / 8','6'],['6.0 mm','J / 10','4'],['8.0 mm','L / 11','0']];$('#hookSelect').innerHTML=hooks.map((x,i)=>`<option value="${i}" ${i==2?'selected':''}>${x[0]} metric hook</option>`).join('');$('#hookSelect').onchange=e=>{let x=hooks[e.target.value];$('#usSize').textContent=x[1];$('#ukSize').textContent=x[2]};$('#glossary').innerHTML=[['ch','Chain'],['sc','Single crochet'],['hdc','Half double crochet'],['dc','Double crochet'],['tr','Treble crochet']].map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span><span>⌁</span></div>`).join('');
let count=+localStorage.getItem('virka-count')||0;function counter(){count=Math.max(0,count);$('#count').textContent=count;localStorage.setItem('virka-count',count)}counter();$('#plus').onclick=()=>{count++;counter()};$('#minus').onclick=()=>{count--;counter()};$('#reset').onclick=()=>{count=0;counter()};$('#estimate').onclick=()=>{let base={Hat:150,Sweater:900,Blanket:1200}[$('#project').value],mul={Small:.8,Medium:1,Large:1.3}[$('#size').value];$('#estimateResult').textContent=`Estimated yarn: about ${Math.round(base*mul)} yards. Always check your pattern and gauge.`};
$('#theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('virka-theme',document.body.classList.contains('dark'))};if(localStorage.getItem('virka-theme')==='true')document.body.classList.add('dark');$('.menu').onclick=()=>$('#nav').classList.toggle('open');$('#searchBtn').onclick=()=>{$('#patterns').scrollIntoView();$('#patternSearch').value=$('#search').value;page=1;draw()};$('#support').onclick=()=>{openAuth('signup','Support is a demo contact flow. Create an account to continue.')};
$('#profile').onclick=()=>$('#accountMenu').classList.toggle('hidden');$('#signOut').onclick=async()=>{await signOutUser();clearUser();notify('You have been signed out.','success')};$('#adminPublish').onclick=()=>{$('#accountMenu').classList.add('hidden');$('#modalContent').innerHTML=`<h2>Publish pattern</h2><p>Admin access confirmed. Publish website content from Sanity Studio so it appears on the live website.</p><a class="coral-btn pdf-link" href="https://virkacrafts-studio.vercel.app" target="_blank" rel="noopener">Open Sanity Studio</a>`;modal.showModal()}

// Sanity content is loaded after the CDN client is ready. Existing cards remain
// visible if the dataset is private, empty, or uses different document types.
window.addEventListener('virka-sanity-ready',async()=>{
  try{
    const [cmsPatterns,cmsCourses,cmsGuides,siteSettings]=await Promise.all([
      window.virkaSanity.fetch(`*[_type in ["product","pattern"] && !(_id in path("drafts.**"))] | order(featured desc, _createdAt desc){"id":_id,"title":coalesce(title,name),"category":coalesce(category->title,category,"Patterns"),"difficulty":coalesce(difficulty,"Beginner"),"image":coalesce(mainImage.asset->url,image.asset->url,featuredImage.asset->url),"pdf":coalesce(pdf.asset->url,guidePdf.asset->url),"externalUrl":coalesce(externalUrl,checkoutUrl)}`),
      window.virkaSanity.fetch(`*[_type == "course" && !(_id in path("drafts.**")) && isPublished != false] | order(_createdAt desc){"title":coalesce(title,name),"level":coalesce(level,"Basic"),"summary":coalesce(summary,"Explore this crochet course."),"logo":courseLogo.asset->url,"coverImage":coverImage.asset->url,"sampleImage":sampleImage.asset->url,"symbolImage":symbolImage.asset->url,"lessonImages":lessonImages[].asset->url}`),
      window.virkaSanity.fetch(`*[_type == "guide" && !(_id in path("drafts.**")) && isPublished != false] | order(_createdAt desc){"title":coalesce(title,name),"level":coalesce(level,"Basic"),"us":coalesce(usCode,usAbbreviation,"—"),"uk":coalesce(ukCode,ukAbbreviation,"—"),"symbol":stitchSymbol,"sampleImage":stitchImage.asset->url,"drawingImage":drawingImage.asset->url,"symbolImage":stitchSymbolImage.asset->url,"referenceImages":referenceImages[].asset->url,"instructions":instructions[]{children[]{text}},"instructionPdf":instructionPdf.asset->url}`),
      window.virkaSanity.fetch(`*[_type == "siteSettings" && !(_id in path("drafts.**"))][0]{"siteTitle":coalesce(siteTitle,"VirkaCrafts"),"logo":websiteLogo.asset->url}`)
    ]);
    if(siteSettings?.logo){document.querySelectorAll('.logo').forEach(logo=>{logo.classList.add('has-site-logo');logo.innerHTML=`<img src="${siteSettings.logo}" alt="${siteSettings.siteTitle} logo">`})}
    if(cmsPatterns.length){
      const mapped=cmsPatterns.filter(p=>p.title).map(p=>[p.title,String(p.category),String(p.difficulty),p.image||'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=600&q=80',p.pdf||p.externalUrl||'',p.id]);
      patterns.splice(0,patterns.length,...mapped);page=1;draw();
    }
    if(cmsCourses.length)$('#courseFeed').innerHTML=cmsCourses.map(c=>`<article class="course-card">${c.coverImage||c.sampleImage?`<img class="course-cover" src="${c.coverImage||c.sampleImage}" alt="${c.title||'Course'}">`:''}<div class="course-content">${c.logo?`<img class="course-logo" src="${c.logo}" alt="">`:''}<span class="tag">${c.level} course</span><h3>${c.title||'Crochet course'}</h3><p>${c.summary||''}</p>${c.symbolImage?`<img class="course-symbol" src="${c.symbolImage}" alt="Course symbol">`:''}${c.lessonImages?.length?`<div class="course-gallery">${c.lessonImages.map((image,index)=>`<img src="${image}" alt="${c.title||'Course'} lesson ${index+1}">`).join('')}</div>`:''}</div></article>`).join('');
    if(cmsGuides.length){
      loadedGuides=cmsGuides;
      $('#stitchTable').innerHTML=`<div class="stitch-row head"><span>Sample</span><span>Name & symbol</span><span>Drawing</span><span>US code</span><span>UK code</span><span>How to make</span><span></span></div>`+cmsGuides.map((g,i)=>`<div class="stitch-row"><div class="stitch-sample">${g.sampleImage?`<img class="zoomable" data-zoom="${g.sampleImage}" src="${g.sampleImage}" alt="${g.title||'Stitch'} sample">`:`<i class="swatch" style="filter:hue-rotate(${i*35}deg)"></i>`}</div><div class="guide-name"><b>${g.title||'Stitch guide'}</b><span class="guide-symbol">${g.symbolImage?`<img class="zoomable" data-zoom="${g.symbolImage}" src="${g.symbolImage}" alt="${g.symbol||'Stitch symbol'}">`:g.symbol||''}</span></div><div class="stitch-drawing">${g.drawingImage?`<img class="zoomable" data-zoom="${g.drawingImage}" src="${g.drawingImage}" alt="${g.title||'Stitch'} drawing">`:'<span class="drawing-placeholder">—</span>'}</div><span class="stitch-code">${g.us}</span><span class="stitch-code">${g.uk}</span><div class="steps">${(g.referenceImages||[]).slice(0,3).map((image,index)=>`<img class="zoomable" data-zoom="${image}" src="${image}" alt="Step ${index+1}">`).join('')||'<i></i><i></i><i></i>'}</div><button class="read" data-guide="${i}">Read instructions</button></div>`).join('');
    }
  }catch(error){console.info('Sanity content was unavailable; showing local fallback content.',error.message)}
});
